package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HttpsGithubComDariaKrupGradleSimpleRefsHeadsMaster'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HttpsGithubComDariaKrupGradleSimpleRefsHeadsMaster")) {
    val expected = GitVcsRoot({
        id("HttpsGithubComDariaKrupGradleSimpleRefsHeadsMaster")
        name = "https://github.com/DariaKrup/gradle-simple#refs/heads/master"
        url = "https://github.com/DariaKrup/gradle-simple"
        branch = "refs/heads/master"
        branchSpec = "refs/heads/*"
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_8685218e5cd3c0b26494694db56f82fb:-1:3b671de5-34c1-4b7a-b465-f516f4abff5c"
        }
        param("tokenType", "refreshable")
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_307e784e3150e3601101135bd8cbad26:-1:62ec6eca-d998-40cf-9aca-c8c9c690bb31"
        }
        param("tokenType", "")
    }

}
